### ISSUE TITLE
Try to rewrite file source code using `ghc-exactprint`

### ISSUE THREAD

**Issue by chshersh** [kowainik/smuggler#21]

**Comment by chshersh** [comment]
@vrom911 Using `ghc-exactprint` as a local dependency involve more steps than I expected... I need to download some dependencies locally. Not sure that I can write script for this. Are you okay with this as a temporary solution?

**Comment by vrom911** [comment]
Yes, I see. Let's keep this as a temporary solution. 
But also I would ask you to share the instructions for that somewhere, please.
