### ISSUE TITLE
Investigate how to remove symbol from 'Anns'

### ISSUE THREAD

**Issue by chshersh** [kowainik/smuggler#4]
Use `debugAST` function to see how it works.

**Comment by vrom911** [comment]
I have tried to remove some symbols. What I was doing is searching map by `SrcSpan` locations by line and starting position, as I guess it's always enough for our needs. It works fine with different type of constructions.

**Comment by chshersh** [comment]
@vrom911 That's really :cool: :100: :top: 
If you could create function which takes required parameters as arguments, that will be the first great step towards our implementation!
