### ISSUE TITLE
cabal.project should not hard code location of ghc

### ISSUE THREAD

**Issue by mpickering** [kowainik/smuggler#43]
For example, on NixOS, this is not where GHC is located and the line has to be removed before the project is built.

**Comment by chshersh** [comment]
@mpickering That's fair point. I guess renaming `cabal.project` to `cabal.project.local` should fix the problem.

**Comment by chshersh** [comment]
@mpickering There's no `cabal.project` file anymore (since it's not needed after GHC release). So I guess the issue should be resolved.
