### ISSUE TITLE
Fix warnings in app/Main

### ISSUE THREAD

**Issue by v0d1ch** [kowainik/smuggler#49]
There are some warnings about unused imports in `app/Main` that need fixing.

**Comment by chshersh** [comment]
@v0d1ch Actually, these warnings shouldn't be fixed. The warnings are only about unused imports. I use `app/Main.hs` file to test how `smuggler` works. Maybe there exist better strategy for doing so? 🤔

**Comment by v0d1ch** [comment]
Oh ok. I think ideal thing would be similar to what ghc does with tests that expect failure https://github.com/ghc/ghc/blob/master/testsuite/tests/printer/all.T#L57 . I am not too sure if you can do that with hspec or hedgehog and then this would live in tests. I will close this PR now and we can open another one when we have more info.

**Comment by chshersh** [comment]
@v0d1ch We already have automated tests for `smuggler` using golden testing technique! But it's good to have some playground where you can test how `smuggler` works. Since it's a GHC source plugin and not some external tool, I need to have some compilation stanza to play with source plugin.
