### ISSUE TITLE
Stack build osx for 8.6+ failing

### ISSUE THREAD

**Issue by Cmdv** [kowainik/smuggler#54]
I tried to follow the instructions to get things built:
`STACK_YAML=stack-mac-8.6.1.yaml stack build`

but I get this error:
```
Getting project config file from STACK_YAML environment
Error parsing targets: The project contains no local packages (packages not marked with 'extra-dep')
```
Any idea what I might be doing wrong, I've deleted my `.stack-work/` but still seems that I'm running on `ghc 8.4.3` 🤔

**Comment by chshersh** [comment]
@Cmdv there's open PR by @v0d1ch 

* https://github.com/kowainik/smuggler/pull/48

I hope that after the PR is merged, you should be able to build `smuggler` without problems :ok_hand:

**Comment by Cmdv** [comment]
ah lovely, good ol @v0d1ch is on the case!

**Comment by chshersh** [comment]
@Cmdv Should be fixed now :ok_hand:

**Comment by Cmdv** [comment]
lovely thanks 👍
