### ISSUE TITLE
Learn to remove commas in data type list

### ISSUE THREAD

**Issue by chshersh** [kowainik/smuggler#7]

**Comment by chshersh** [comment]
Okay, I've tested compilation on simple files.

This code compiles:

```haskell
import Data.Bool (Bool,)
```

And this code doesn't compile with parse error:

```haskell
import Data.Bool (Bool (True,))
```

Personally, I find this behaviour extremely inconsistent. So I've created GHC ticket for that:

* https://ghc.haskell.org/trac/ghc/ticket/15392

**Comment by Cmdv** [comment]
was going to give this a try, where in the codebase would this live?

**Comment by chshersh** [comment]
@Cmdv I think, that placing this functionality into `Smuggler.Anns` module should be okay. There's already a function that deletes entry occurrence:

* https://github.com/kowainik/smuggler/blob/master/src/Smuggler/Anns.hs

You may find this module useful in debugging purposes:

* https://github.com/kowainik/smuggler/blob/master/src/Smuggler/Debug.hs

But you need to uncomment it and some dependencies in the `.cabal` file.
